version: "3.5"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3333:3306
    volumes:
      - ./db-mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.1.1
    restart: always
    ports:
      - 8888:80

  web-server:
    image: ${WEB_SERVER_IMAGE}
    ports:
      - 3000:3000
    volumes:
      - ./videos:/usr/src/app/volume-folder
    environment:
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - JWT_SECRET
      - JWT_LOGINTOKEN_SECRET
      - NESTO
    restart: always
    depends_on:
      - db

  front:
    image: ${FRONT_IMAGE}
    ports:
      - 5000:80
    restart: always
